#!/usr/bin/env sh

# Format staged files with Prettier
pnpm exec lint-staged
# Lint workspace (via Turbo pipeline)
pnpm lint --output-logs=none

# typecheck workspace (via Turbo pipeline)
pnpm typecheck --output-logs=none
